name: CI
on:
  push:
    branches: code

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@main

      # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
      # - name: Update theme
      #   run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.64.0"

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo #--minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: fpkmatthi/fpkmatthi.github.io
          publish_dir: ./public
          #   keep_files: true
          user_name: fpkmatthi
          user_email: skymatth@gmail.com
          publish_branch: master
          cname: me.fpkmatthi.xyz
